version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - gradle clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=509399628928.dkr.ecr.ap-south-1.amazonaws.com/khelmates-registry
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Fetching MongoDB URI from Parameter Store...
      - MONGODB_URI=$(aws ssm get-parameter --name "/khelmates/mongodb/uri" --with-decryption --region ap-south-1 --query "Parameter.Value" --output text)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg MONGODB_URI="$MONGODB_URI" -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=khelmates-registry
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - build/libs/demo-0.0.1-SNAPSHOT.jar
